osx_image: xcode7.3
language: objective-c
sudo: false
env:
  global:
  - IOS_SDK=iphonesimulator9.3
  - IOS_SCHEME="DTModelStorage-iOS"
  - TVOS_SDK=appletvsimulator9.2
  - TVOS_SCHEME="DTModelStorage-tvOS"

  matrix:
  - DESTINATION="OS=9.3,name=iPad 2"         SDK="$IOS_SDK"  SCHEME="$IOS_SCHEME"
  - DESTINATION="OS=9.3,name=iPad Air"       SDK="$IOS_SDK"  SCHEME="$IOS_SCHEME"
  - DESTINATION="OS=9.3,name=iPhone 5"       SDK="$IOS_SDK"  SCHEME="$IOS_SCHEME"
  - DESTINATION="OS=9.3,name=iPhone 6s"      SDK="$IOS_SDK"  SCHEME="$IOS_SCHEME"
  - DESTINATION="OS=8.4,name=iPhone 6"       SDK="$IOS_SDK"  SCHEME="$IOS_SCHEME"
  - DESTINATION="OS=8.4,name=iPad Air"       SDK="$IOS_SDK"  SCHEME="$IOS_SCHEME"
  - DESTINATION="OS=9.2,name=Apple TV 1080p" SDK="$TVOS_SDK" SCHEME="$TVOS_SCHEME"

before_install:
- git submodule foreach --recursive git submodule update --init
- gem install xcpretty --no-document
- cd DTModelStorageTests

script:
- set -o pipefail
- xcodebuild -version
- xcodebuild -project DTModelStorage.xcodeproj -scheme "$SCHEME" -configuration Debug
  -sdk "$SDK" -destination "$DESTINATION" test -enableCodeCoverage YES "IDEBuildOperationMaxNumberOfConcurrentCompileTasks=`sysctl
  -n hw.ncpu`" | xcpretty
after_success:
- bash <(curl -s https://codecov.io/bash)
