osx_image: xcode7
language: objective-c

before_install:
- gem install cocoapods --no-document
- gem install xcpretty --no-document
- cd DTModelStorageTests
- pod install

script:
    - xcodebuild test -workspace DTModelStorage.xcworkspace -scheme XCTests -configuration Debug -destination "platform=iOS Simulator,name=iPhone 4s" -destination "platform=iOS Simulator,name=iPhone 6 Plus" GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty -c

after_success:
    - bash <(curl -s https://codecov.io/bash)
