osx_image: xcode7
language: objective-c

before_install:
- sudo gem install cocoapods --no-document --quiet
- sudo gem install xcpretty --no-document --quiet
- export LANG=en_US.UTF-8
- cd DTModelStorageTests

script: rake
